# Generated by Django 2.2.1 on 2019-05-26 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artName', models.CharField(max_length=200)),
                ('artContent', models.TextField()),
                ('artViews', models.IntegerField(default=0)),
                ('artDate', models.DateTimeField(auto_now=True)),
                ('artImg', models.CharField(max_length=255)),
                ('artAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('artCat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='catName')),
            ],
        ),
    ]
