# Generated by Django 2.2.1 on 2019-05-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='artImg',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
