# Generated by Django 2.2.1 on 2019-05-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190526_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='artUrl',
            field=models.CharField(default='d-sdsds-asd', max_length=255),
        ),
    ]
