# Generated by Django 2.2.1 on 2019-05-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_arturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='artUrl',
            field=models.CharField(max_length=255),
        ),
    ]
